/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import static com.sun.org.apache.regexp.internal.RETest.test;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.table.TableColumn;
import javax.swing.text.TableView.TableRow;
import static jdk.nashorn.internal.objects.NativeRegExp.test;

/**
 *
 * @author 30179793
 */
public class MainFrame extends javax.swing.JFrame {
    Airline air = new Airline();
    Flight flight = new Flight();
    HashMap flights;
    Seat seat = new Seat();
    HashMap seats = new HashMap(200);


    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws SQLException {
        initComponents();
        btnGroupStatus.add(rBtnBoarding);
        btnGroupStatus.add(rBtnBooking);
        btnGroupStatus.add(rBtnChecking);
        btnGroupStatus.add(rBtnClosed);
        btnGroupPassenger.add(rBtnOrdinary);
        btnGroupPassenger.add(rBtnBuisness);
        btnGroupPassenger.add(rBtnIsland);
        try
        {
            air.loadFlights();
            flights = air.getFlights();
            for(int i = 0; i <= flights.size() - 1; i++)
            {
                Flight temp = (Flight) flights.get(String.valueOf(i));
                temp.loadSeats();
                flightNumCombo.addItem(temp.getFlightNum());
            }
        }
        
        catch(Exception ex)
            {
                ex.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupStatus = new javax.swing.ButtonGroup();
        btnGroupPassenger = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        pnlAddFlight = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        txtDeparture = new javax.swing.JTextField();
        txtArrival = new javax.swing.JTextField();
        btnAddFlight = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtColumns = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRows = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        seatCombo = new javax.swing.JComboBox<>();
        btnBookSeat = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rBtnOrdinary = new javax.swing.JRadioButton();
        rBtnBuisness = new javax.swing.JRadioButton();
        rBtnIsland = new javax.swing.JRadioButton();
        txtBuisness = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnReserveSeat = new javax.swing.JButton();
        lblBook = new javax.swing.JLabel();
        lblReservedDetails = new javax.swing.JPanel();
        lblFlightNumDetails = new javax.swing.JLabel();
        lblFlightNum = new javax.swing.JLabel();
        lblDeparture = new javax.swing.JLabel();
        lblDepartureDetails = new javax.swing.JLabel();
        lblArrivalDetails = new javax.swing.JLabel();
        lblArrival = new javax.swing.JLabel();
        lblBookingAvailable = new javax.swing.JLabel();
        lblCheckingIn = new javax.swing.JLabel();
        lblBoardingAvailableDetails = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblColumnsDetails = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblRowsOut = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        lblTimeDetails = new javax.swing.JLabel();
        lblCheckingInDetails = new javax.swing.JLabel();
        lblBoardingDetails = new javax.swing.JLabel();
        lblClosedDetails = new javax.swing.JLabel();
        lblColumns = new javax.swing.JLabel();
        lblRows = new javax.swing.JLabel();
        lblClosed = new javax.swing.JLabel();
        lblBoarding = new javax.swing.JLabel();
        lblFreeSeatsDetails = new javax.swing.JLabel();
        lblFreeSeats = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblReservedSeats = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBookedSeats = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        flightNumCombo = new javax.swing.JComboBox<>();
        btnViewFlight = new javax.swing.JButton();
        btnSelectFlight = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        rBtnChecking = new javax.swing.JRadioButton();
        rBtnBoarding = new javax.swing.JRadioButton();
        rBtnClosed = new javax.swing.JRadioButton();
        rBtnBooking = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblPassName = new javax.swing.JLabel();
        lblBuisName = new javax.swing.JLabel();
        lblPassType = new javax.swing.JLabel();
        lblSeatPrice = new javax.swing.JLabel();
        lblSeatTakings = new javax.swing.JLabel();
        lblFlightId = new javax.swing.JLabel();
        viewSeatCombo = new javax.swing.JComboBox<>();
        btnViewSeatDetails = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnCancelSeat = new javax.swing.JButton();
        lblCancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Flight number");

        jLabel2.setText("Departure airport");

        jLabel3.setText("Arrival airport");

        btnAddFlight.setText("Add Flight");
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        jLabel5.setText("Columns");

        jLabel15.setText("Rows");

        jLabel16.setText("Date");

        jLabel17.setText("Time");

        javax.swing.GroupLayout pnlAddFlightLayout = new javax.swing.GroupLayout(pnlAddFlight);
        pnlAddFlight.setLayout(pnlAddFlightLayout);
        pnlAddFlightLayout.setHorizontalGroup(
            pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddFlightLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(67, 67, 67)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddFlightLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(66, 66, 66)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddFlightLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(63, 63, 63)
                        .addComponent(txtRows, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddFlightLayout.createSequentialGroup()
                        .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddFlight)
                            .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)))
                        .addGap(5, 5, 5)
                        .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeparture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(txtArrival)
                            .addComponent(txtFlightNumber)
                            .addComponent(txtColumns))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddFlightLayout.setVerticalGroup(
            pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlAddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnAddFlight)
                .addContainerGap())
        );

        jLabel19.setText("Seat number");

        btnBookSeat.setText("Book seat");
        btnBookSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSeatActionPerformed(evt);
            }
        });

        jLabel23.setText("Passenger Name");

        jLabel8.setText("Type of Passenger");

        rBtnOrdinary.setText("Ordinary Passenger");

        rBtnBuisness.setText("Buisness Passenger");

        rBtnIsland.setText("Island Passenger");

        jLabel9.setText("Buisness Name");

        lblError.setForeground(new java.awt.Color(255, 51, 51));

        btnReserveSeat.setText("Reserve Seat");
        btnReserveSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveSeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName)
                                    .addComponent(seatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuisness, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnOrdinary)
                            .addComponent(rBtnIsland)
                            .addComponent(rBtnBuisness))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnReserveSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(btnBookSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(seatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(rBtnOrdinary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnBuisness)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnIsland)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuisness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookSeat)
                    .addComponent(btnReserveSeat))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(lblBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblFlightNumDetails.setText("Flight Number:");

        lblDepartureDetails.setText("Departure Airport:");

        lblArrivalDetails.setText("Arrival Airport:");

        lblBoardingAvailableDetails.setText("Booking Available");

        lblColumnsDetails.setText("Columns");

        lblRowsOut.setText("Rows");

        lblDetails.setText("Date");

        lblTimeDetails.setText("Time");

        lblCheckingInDetails.setText("Checking In");

        lblBoardingDetails.setText("Boarding");

        lblClosedDetails.setText("Closed");

        lblFreeSeatsDetails.setText("Free Seats");

        jLabel6.setText("Reserved Seats");

        jLabel7.setText("Booked Seats");

        javax.swing.GroupLayout lblReservedDetailsLayout = new javax.swing.GroupLayout(lblReservedDetails);
        lblReservedDetails.setLayout(lblReservedDetailsLayout);
        lblReservedDetailsLayout.setHorizontalGroup(
            lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblReservedDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblReservedDetailsLayout.createSequentialGroup()
                        .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFlightNumDetails)
                            .addComponent(lblDepartureDetails)
                            .addComponent(lblArrivalDetails)
                            .addComponent(lblBoardingAvailableDetails)
                            .addComponent(lblColumnsDetails)
                            .addComponent(lblRowsOut)
                            .addComponent(lblCheckingInDetails)
                            .addComponent(lblBoardingDetails)
                            .addComponent(lblClosedDetails))
                        .addGap(32, 32, 32)
                        .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeparture, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lblFlightNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblArrival, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBookingAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCheckingIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblColumns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClosed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBoarding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lblReservedDetailsLayout.createSequentialGroup()
                        .addComponent(lblDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblReservedDetailsLayout.createSequentialGroup()
                        .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimeDetails)
                            .addComponent(lblFreeSeatsDetails)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lblFreeSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReservedSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBookedSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        lblReservedDetailsLayout.setVerticalGroup(
            lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblReservedDetailsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightNumDetails)
                    .addComponent(lblFlightNum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartureDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrivalDetails)
                    .addComponent(lblArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookingAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardingAvailableDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCheckingIn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckingInDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBoardingDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBoarding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClosed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClosedDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRowsOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblColumns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColumnsDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblReservedDetailsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimeDetails))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblReservedDetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFreeSeatsDetails)
                    .addComponent(lblFreeSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblReservedSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblReservedDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblBookedSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Flight number");

        btnViewFlight.setText("view flight details");
        btnViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightActionPerformed(evt);
            }
        });

        btnSelectFlight.setText("Select Flight");
        btnSelectFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFlightActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update status");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        rBtnChecking.setText("checking in");
        rBtnChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCheckingActionPerformed(evt);
            }
        });

        rBtnBoarding.setText("boarding");

        rBtnClosed.setText("closed");
        rBtnClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnClosedActionPerformed(evt);
            }
        });

        rBtnBooking.setText("booking available");
        rBtnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnChecking)
                    .addComponent(rBtnBooking)
                    .addComponent(rBtnBoarding)
                    .addComponent(rBtnClosed)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(flightNumCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnViewFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelectFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(flightNumCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectFlight)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewFlight)
                .addGap(18, 18, 18)
                .addComponent(rBtnBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnChecking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnBoarding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnClosed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Passenger Name");

        jLabel11.setText("buisness name");

        jLabel12.setText("type of passenger");

        jLabel13.setText("Seat Price");

        jLabel14.setText("Seat Takings");

        jLabel18.setText("Flight id");

        btnViewSeatDetails.setText("View Seat Details");
        btnViewSeatDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSeatDetailsActionPerformed(evt);
            }
        });

        jLabel20.setText("Status");

        btnCancelSeat.setText("Cancel Seat");
        btnCancelSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPassName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBuisName, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassType, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(lblSeatPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSeatTakings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFlightId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(viewSeatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewSeatDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblBuisName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblPassType, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblSeatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblSeatTakings, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSeatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewSeatDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelSeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblReservedDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblReservedDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed

        flight = new Flight(txtFlightNumber.getText(), txtArrival.getText(), txtDeparture.getText(), Integer.parseInt(txtColumns.getText()), Integer.parseInt(txtRows.getText()), txtDate.getText(), txtTime.getText());
        flight.generateSeats();
        flights.put(flight.getFlightNum(), flight);
        air.setFlights(flights);
        flightNumCombo.addItem(flight.getFlightNum());
        air.saveDb();
    }//GEN-LAST:event_btnAddFlightActionPerformed

    private void rBtnCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCheckingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnCheckingActionPerformed

    private void rBtnClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnClosedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnClosedActionPerformed

    private void rBtnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnBookingActionPerformed

    private void btnViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightActionPerformed

        lblFlightNum.setText(flight.getFlightNum());
        lblDeparture.setText(flight.getDeparture());
        lblArrival.setText(flight.getArrival());
        lblColumns.setText(Integer.toString(flight.getColumns()));
        lblRows.setText(Integer.toString(flight.getRows()));
        lblDate.setText(flight.getDate());
        lblTime.setText(flight.getTime());
        lblFreeSeats.setText(Integer.toString(flight.FreeSeats()));
        lblBookedSeats.setText(Integer.toString(flight.BookedSeats()));
        lblReservedSeats.setText(Integer.toString(flight.ReservedSeats()));
        if (flight.getBookingAvailable() == true)
        {
            lblBookingAvailable.setText("Yes");
        }
        else
        {
            lblBookingAvailable.setText("No");
        }
        
        if (flight.getBoarding() == true)
        {
            lblBoarding.setText("Yes");
        }
        else
        {
            lblBoarding.setText("No");
        }
        
        if (flight.getCheckingIn() == true)
        {
            lblCheckingIn.setText("Yes");
        }
        else
        {
            lblCheckingIn.setText("No");
        }
        
        if (flight.getClosed() == true)
        {
            lblClosed.setText("Yes");
        }
        else
        {
            lblClosed.setText("No");
        }

        

        
    }//GEN-LAST:event_btnViewFlightActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (rBtnBooking.isSelected())
        {
            flight.setBookingAvailable(true);
            flight.setBoarding(false);
            flight.setclosed(false);
            flight.setCheckingIn(false);
        }
        else if (rBtnChecking.isSelected())
        {
            flight.setBookingAvailable(false);
            flight.setBoarding(false);
            flight.setclosed(false);
            flight.setCheckingIn(true);
        }
        
        else if (rBtnBoarding.isSelected())
        {
            flight.setBookingAvailable(false);
            flight.setBoarding(true);
            flight.setclosed(false);
            flight.setCheckingIn(false);
        }
        
        else if (rBtnClosed.isSelected())
        {
            flight.setBookingAvailable(false);
            flight.setBoarding(false);
            flight.setclosed(true);
            flight.setCheckingIn(false);
        }
        
        HashMap f = air.getFlights();
        f.remove(flight.getFlightNum());
        f.put(flight.getFlightNum(), flight);
        air.saveDb();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBookSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSeatActionPerformed

        Seat s = new Seat();
        String id = (String) seatCombo.getSelectedItem();
        s = flight.getSeat(id);
        if (!s.getBooked())
        {
            if (s.getReserved())
            {
                if (txtName.getText().equals(s.getName()))
                {
                    s.setBooked(true);
                    
                    lblBook.setText("Seat " + id + " booked by " + s.getName());
                    
                    if (s.getPassenger() instanceof BuisnessPassenger)
                    {
                        lblBook.setText("Seat " + id + " booked by buisness passenger " + txtName.getText());
                    }
                    
                    if (s.getPassenger() instanceof OrdinaryPassenger)
                    {
                        lblBook.setText("Seat " + id + " booked by ordinary passenger " + txtName.getText());
                    }
                    
                    if (s.getPassenger() instanceof IslandPassenger)
                    {
                        lblBook.setText("Seat " + id + " booked by island passenger " + txtName.getText());
                    }
                }
                else
                {
                    lblError.setText("This seat is not reserved by that passenger");
                }
            }
            else
            {
            if (rBtnBuisness.isSelected())
            {
                if ("".equals(txtBuisness.getText()))
                {
                    lblError.setText("ERROR: Buisness passengers must enter the name of their buisness");
                }
                else
                {
                    BuisnessPassenger temp = new BuisnessPassenger(txtName.getText(), txtBuisness.getText());
                    s.bookSeat((temp));
                    lblBook.setText("Seat " + id + " booked by buisness passenger " + txtName.getText());
                }
            }

            else if (rBtnOrdinary.isSelected())
            {
                OrdinaryPassenger temp = new OrdinaryPassenger(txtName.getText());
                s.bookSeat((temp));
                lblBook.setText("Seat " + id + " booked by ordinary passenger " + txtName.getText());
            }

            else if (rBtnIsland.isSelected())
            {
                IslandPassenger temp = new IslandPassenger(txtName.getText());
                s.bookSeat((temp));
                lblBook.setText("Seat " + id + " booked by island passenger " + txtName.getText());
            }
            }
            seats.remove(s.getId());
            seats.put(s.getId(), s);
            flight.setSeats(seats);
            flight.bookingMade();
            
        }
        else
        {
            lblError.setText("That seat is already booked");
        }
        air.saveDb();
    }//GEN-LAST:event_btnBookSeatActionPerformed

    private void btnSelectFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFlightActionPerformed
        air.saveDb();
        String t = (String) flightNumCombo.getSelectedItem();
        flight = (Flight) flights.get(t);
        seats = flight.getSeats();
        char[] row = "abcdefghijklmnopqrstuvwxyz".toUpperCase().toCharArray();
        seatCombo.removeAllItems();
        viewSeatCombo.removeAllItems();
        for(int i = 0; i <= flight.getRows() - 1; i++)
        {
            for(int j = 1; j <= flight.getColumns(); j++)
            {
                seatCombo.addItem(Character.toString(row[i]) + " " + Integer.toString(j));
                viewSeatCombo.addItem(Character.toString(row[i]) + " " + Integer.toString(j));
            }
            
        }
    }//GEN-LAST:event_btnSelectFlightActionPerformed

    private void btnViewSeatDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSeatDetailsActionPerformed

        Seat temp = new Seat();
        String id = (String) viewSeatCombo.getSelectedItem();
        temp = flight.getSeat(id);
        lblBuisName.setText("");
        if (!temp.getName().equals(""))
        {
            lblPassName.setText(temp.getName());
        }
        
        else
        {
            lblPassName.setText("");
        }
        lblBuisName.setText("");
        lblPassType.setText("");
        lblSeatPrice.setText("");
        lblSeatTakings.setText("");
        lblFlightId.setText("");
        lblStatus.setText("");

        if (temp.getPassenger() instanceof BuisnessPassenger)
        {
            BuisnessPassenger p = (BuisnessPassenger) temp.getPassenger();
            lblBuisName.setText(p.getBuisnessName());
            lblPassType.setText("Buisness Passenger");
            lblSeatPrice.setText(Integer.toString(temp.getPrice()));
            lblSeatTakings.setText(Float.toString(temp.getTakings()));
            lblFlightId.setText(flight.getFlightNum());

        }
        
        if (temp.getPassenger() instanceof OrdinaryPassenger)
        {
            OrdinaryPassenger p = (OrdinaryPassenger) temp.getPassenger();
            lblBuisName.setText("");
            lblPassType.setText("Ordinary Passenger");
            lblSeatPrice.setText(Integer.toString(temp.getPrice()));
            lblSeatTakings.setText(Float.toString(temp.getTakings()));
            lblFlightId.setText(flight.getFlightNum());
        }
        
        if (temp.getPassenger() instanceof IslandPassenger)
        {
            IslandPassenger p = (IslandPassenger) temp.getPassenger();
            lblBuisName.setText("");
            lblPassType.setText("Island Passenger");
            lblSeatPrice.setText(Integer.toString(temp.getPrice()));
            lblSeatTakings.setText(Float.toString(temp.getTakings()));
            lblFlightId.setText(flight.getFlightNum());
        }
        
        
        if (temp.getBooked())
            {
                lblStatus.setText("Booked");
            }
            else if (temp.getReserved())
            {
                lblStatus.setText("Reserved");
            }
            
            else if (!temp.getBooked() && !temp.getReserved())
            {
                lblStatus.setText("Available");
                lblPassName.setText("");
            }
    }//GEN-LAST:event_btnViewSeatDetailsActionPerformed

    private void btnReserveSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveSeatActionPerformed
        Seat s = new Seat();
        String id = (String) seatCombo.getSelectedItem();
        s = flight.getSeat(id);
        if (s.getReserved() == false && s.getBooked() == false)
        {
            if (rBtnBuisness.isSelected())
            {
                if ("".equals(txtBuisness.getText()))
                {
                    lblError.setText("ERROR: Buisness passengers must enter the name of their buisness");
                }
                else
                {
                    BuisnessPassenger temp = new BuisnessPassenger(txtName.getText(), txtBuisness.getText());
                    s.setPassenger(temp);
                    s = s.reserveSeat((s));
                    lblBook.setText("Seat " + id + " reserved by buisness passenger " + txtName.getText());
                }
            }

            else if (rBtnOrdinary.isSelected())
            {
                OrdinaryPassenger temp = new OrdinaryPassenger(txtName.getText());
                s.setPassenger(temp);
                s = s.reserveSeat((s));
                lblBook.setText("Seat " + id + " reserved by ordinary passenger " + txtName.getText());
            }

            else if (rBtnIsland.isSelected())
            {
                IslandPassenger temp = new IslandPassenger(txtName.getText());
                s.setPassenger(temp);
                s = s.reserveSeat((s));
                lblBook.setText("Seat " + id + " reserved by islnad passenger " + txtName.getText());
            }
            seats.remove(s.getId());
            seats.put(s.getId(), s);
            flight.setSeats(seats);
            flight.reservationMade();
            air.saveDb();
        }
        
        else
        {
            lblError.setText("That seat has already been taken");
        }
    }//GEN-LAST:event_btnReserveSeatActionPerformed

    private void btnCancelSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSeatActionPerformed
        String selected = (String) viewSeatCombo.getSelectedItem();
        Seat temp = new Seat();
        seat = flight.getSeat(selected);
        temp.setId(seat.getId());
        if (seat.getReserved())
        {
            flight.reservationCanceled();
            seats.remove(selected);
            seats.put(selected, temp);
            lblCancel.setText("Canceled reservation of seat " + selected);
        }
        
        else if (seat.getBooked())
        {
            flight.bookingCanceled();
            seats.remove(selected);
            seats.put(selected, temp);
            lblCancel.setText("Canceled booking of seat " + selected);
        }
        
        else
        {
            lblCancel.setText("Cannot cancel booking or reservation of seat " + selected + ", as it is not currently booked or reserved.");
        }
        
        air.saveDb();
    }//GEN-LAST:event_btnCancelSeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JButton btnBookSeat;
    private javax.swing.JButton btnCancelSeat;
    private javax.swing.ButtonGroup btnGroupPassenger;
    private javax.swing.ButtonGroup btnGroupStatus;
    private javax.swing.JButton btnReserveSeat;
    private javax.swing.JButton btnSelectFlight;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewFlight;
    private javax.swing.JButton btnViewSeatDetails;
    private javax.swing.JComboBox<String> flightNumCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblArrival;
    private javax.swing.JLabel lblArrivalDetails;
    private javax.swing.JLabel lblBoarding;
    private javax.swing.JLabel lblBoardingAvailableDetails;
    private javax.swing.JLabel lblBoardingDetails;
    private javax.swing.JLabel lblBook;
    private javax.swing.JLabel lblBookedSeats;
    private javax.swing.JLabel lblBookingAvailable;
    private javax.swing.JLabel lblBuisName;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblCheckingIn;
    private javax.swing.JLabel lblCheckingInDetails;
    private javax.swing.JLabel lblClosed;
    private javax.swing.JLabel lblClosedDetails;
    private javax.swing.JLabel lblColumns;
    private javax.swing.JLabel lblColumnsDetails;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDeparture;
    private javax.swing.JLabel lblDepartureDetails;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFlightId;
    private javax.swing.JLabel lblFlightNum;
    private javax.swing.JLabel lblFlightNumDetails;
    private javax.swing.JLabel lblFreeSeats;
    private javax.swing.JLabel lblFreeSeatsDetails;
    private javax.swing.JLabel lblPassName;
    private javax.swing.JLabel lblPassType;
    private javax.swing.JPanel lblReservedDetails;
    private javax.swing.JLabel lblReservedSeats;
    private javax.swing.JLabel lblRows;
    private javax.swing.JLabel lblRowsOut;
    private javax.swing.JLabel lblSeatPrice;
    private javax.swing.JLabel lblSeatTakings;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeDetails;
    private javax.swing.JPanel pnlAddFlight;
    private javax.swing.JRadioButton rBtnBoarding;
    private javax.swing.JRadioButton rBtnBooking;
    private javax.swing.JRadioButton rBtnBuisness;
    private javax.swing.JRadioButton rBtnChecking;
    private javax.swing.JRadioButton rBtnClosed;
    private javax.swing.JRadioButton rBtnIsland;
    private javax.swing.JRadioButton rBtnOrdinary;
    private javax.swing.JComboBox<String> seatCombo;
    private javax.swing.JTextField txtArrival;
    private javax.swing.JTextField txtBuisness;
    private javax.swing.JTextField txtColumns;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRows;
    private javax.swing.JTextField txtTime;
    private javax.swing.JComboBox<String> viewSeatCombo;
    // End of variables declaration//GEN-END:variables
}
